---

- hosts: all
  become: true
  vars_files:
    - vars.yml

  tasks:

  - name: Get the platform (i386 or amd64) of the virtual machine
    command: dpkg --print-architecture
    register: print_architecture

  - name: And set the actual platform value as a variable
    set_fact:
      platform: "{{ print_architecture.stdout }}"

  - name: Install packages for ODK-X
    apt:
      pkg:
      - unzip
      - vim
      - curl
      - expect
      - python-pexpect
      - openjdk-8-jdk
      - python-pip
      - docker.io
      - maven
      - git
      - software-properties-common
      - gnupg-agent
      - ca-certificates
      - apt-transport-https

  - name: Update and upgrade apt packages
    apt:
      upgrade: safe
      update_cache: yes
      cache_valid_time: 86400 #One day

  - name: Make sure Docker autostarts and is started
    service: name=docker enabled=yes state=started

  - name: Install Docker for Python to handle Docker from Ansible
    pip: 
      name:
        - docker
        - jsondiff

  - name: Clone ODK Sync EndPoints Repo
    git:
      repo: 'https://github.com/opendatakit/sync-endpoint'
      depth: 1
      version: 'master'
      dest: /usr/local/sync-endpoint

  - name: Use Maven to Build ODK Sync EndPoints (SLOW)
    command: mvn clean install -DskipTests
    args:
      chdir: /usr/local/sync-endpoint
    register: results
    
  - name: Maven Build Results
    debug:
      msg: '{{ results.stdout_lines[-16:] }}'

  - name: Clone ODK Sync EndPoints Default Setup Repo
    git:
      repo: 'https://github.com/opendatakit/sync-endpoint-default-setup'
      depth: 1
      version: 'master'
      dest: /usr/local/sync-endpoint-default-setup

  - name: Init a new swarm with default parameters
    docker_swarm:
      state: present

  - name: Setup ODK Sync EndPoint WebUI Docker Image
    shell: docker build --pull -t odk/sync-web-ui https://github.com/ojw713/sync-endpoint-web-ui.git
    args:
      chdir: /usr/local

  - name: Setup ODK DB-Bootstrap Docker Image
    docker_image:
      name: odk/db-bootstrap
      build:
        pull: true
        path: /usr/local/sync-endpoint-default-setup/db-bootstrap
      source: build

  - name: Setup ODK OpenLDAP Docker Image
    docker_image:
      name: odk/openldap
      build:
        pull: true
        path: /usr/local/sync-endpoint-default-setup/openldap
      source: build

  - name: Setup ODK PHP LDAP Admin Docker Image
    docker_image:
      name: odk/phpldapadmin
      build:
        pull: true
        path: /usr/local/sync-endpoint-default-setup/phpldapadmin
      source: build

  - name: Update the Server HTTP Port
    lineinfile:
      path: /usr/local/sync-endpoint-default-setup/config/sync-endpoint/security.properties
      line: "security.server.port=8081"
      create: true

  - name: Insert Updated Port in docker-compose.yml
    blockinfile:
      path: /usr/local/sync-endpoint-default-setup/docker-compose.yml
      insertafter: '# - org.opendatakit.aggregate.logging.properties'
      marker: '    # Port Change - Ansible'
      state: present
      content: |2
            ports:
              - 8081:8080

  - name: Deploy ODK EndPoint Sync Docker Stack
    docker_stack:
      state: present
      name: syncldap
      compose:
        - /usr/local/sync-endpoint-default-setup/docker-compose.yml
